### ISSUE TITLE
UPSTREAM_DNS issue

### ISSUE THREAD

**Issue by ACSmith1337** [lancachenet/lancache-dns#100]
Issue Description:
Container restarts when specifying multiple upstream dns servers. It works fine with 1.1.1.1 or "1.1.1.1" but fails to run with "1.1.1.1 1.0.0.1"

Docker Run Command:
```
sudo docker run --restart unless-stopped --name lancache-dns --detach -p 53:53/udp -e USE_GENERIC_CACHE=true -e UPSTREAM_DNS="1.1.1.1 1.0.0.1" -e LANCACHE_IP=192.168.1.12 lancachenet/lancache-dns:latest
```

Docker Container Output:

```
sudo docker stats - shows lancache-dns restarting constantly.
```

**Comment by VibroAxe** [comment]
Hi @ACSmith1337 

Currently we don't support multiple UPSTREAM_DNS correct format will be `UPSTREAM_DNS="1.1.1.1; 1.0.0.1"` however you will need to wait until pr #101 merges

**Comment by ACSmith1337** [comment]
Ah ok. I misunderstood the readme for monolithic. I though it was referring to the lancache-dns not lancache specifically. Thank you!
