### ISSUE TITLE
level3.ssl.blizzard.com broken blizzard cache

### ISSUE THREAD

**Issue by SurferLancelot** [lancachenet/lancache-dns#103]
Issue Description:
 Getting an error when downloading blizzard games
"We're having a problem transferring data. please check your internet connection just in case and try again."

New dns address added by blizzard which is not in steamcache-dns as far as i can tell it needs to be added/bypassed
level3.ssl.blizzard.com

**Comment by SurferLancelot** [comment]
To bypass lancache for this issue until it can be resolved 

`sudo docker exec -i -t "CONTAINER_ID"  /bin/bash`
`apt install nano`
`nano /etc/bind/cache/rpz.db`

```
## blizzard
level3.ssl.blizzard.com IN A 8.241.23.1.;
```

`service bind9 restart`

**Comment by VibroAxe** [comment]
I'm confussed here, the dns container doesn't override level3.ssl.blizzard.com as that is an ssl domain. It should resolve correctly to the upstream dns (which is what your entry appears to do anyway). Can you remove your override and try `nslookup level3.ssl.blizzard.com <yourdnsserverip>`

Not having a domain overridden should never result in errors

**Comment by VibroAxe** [comment]
Also, hard coding that IP is more likely to cause serious issues in the future if the end point server is moved by level3
