### ISSUE TITLE
Blizzard game cache not works

### ISSUE THREAD

**Issue by yangcaixing** [lancachenet/lancache-dns#121]
### Describe the issue you are having
When download Blizzard games, the traffic go through from local internet, not via lancache server, I already add the DNS items forward to lancache, but I find when I download blizzard game, it access to this DNS site "http://client05.pdl.wow.battlenet.com.cn/tpr/hs/data/1c/d3/1cd31f51f8d03125f1f19705a5346141", it not include in Lancache-DNS, How can I add it to Lancache-DNS ,thanks very much.

### How are you running the container(s)
docker-compose up -d
```
<!-- Paste your docker run commands or your docker-compose file here -->
```
version: '2'
services:
  dns:
    image: lancachenet/lancache-dns:latest
    env_file: .env
#    restart: unless-stopped
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp

## you could choose to return to sniproxy if desired
#
#  sniproxy:
#    image: lancachenet/sniproxy:latest
#    env_file: .env
#    restart: unless-stopped
#    ports:
#      - 443:443/tcp

  monolithic:
    image: lancachenet/monolithic:latest
    env_file: .env
#    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
### DNS Configuration
USE_GENERIC_CACHE=true

## Note: This setting only affects DNS, monolithic and sniproxy will still bind to all IPs by default
LANCACHE_IP=172.20.90.247

## IP address on the host that the DNS server should bind to
DNS_BIND_IP=172.20.90.247

## DNS Resolution for forwarded DNS lookups
UPSTREAM_DNS=114.114.114.114
```
<!-- Paste your docker run command for the DNS container OR explain how you have setup DNS on your network to point to the container -->
```
In windows DNS server, Add steam/blizzard condition forward to Lancache-DNS.
### Output of container(s)

```
<!-- Paste any output from the containers here - This will help us identify any issues faster -->
```
[blizzard] 172.20.60.52 / - - - [05/Jan/2021:09:34:15 +0000] "GET /geoip HTTP/1.1" 204 0 "-" "Bootstrapper/1.17.1.3061" "MISS" "nydus.battle.net" "-"
[blizzard] 172.20.60.52 / - - - [05/Jan/2021:09:40:19 +0000] "GET /geoip HTTP/1.1" 204 0 "-" "Bootstrapper/1.17.1.3061" "MISS" "nydus.battle.net" "-"
[blizzard] 172.20.60.52 / - - - [05/Jan/2021:10:08:27 +0000] "GET /geoip HTTP/1.1" 204 0 "-" "Bootstrapper/1.17.1.3061" "MISS" "nydus.battle.net" "-"

**Comment by imLiur** [comment]
找到问题解决方法了吗，我也想添加一个新的主机。
