### ISSUE TITLE
ARM64 Docker image for lancache-dns

### ISSUE THREAD

**Issue by kbrierly** [lancachenet/lancache-dns#133]
### Describe the issue you are having
I would like to run just the lancache-dns docker container on my secondary dns server on a raspberry pi. I have no interest in running the  actual file cache on raspberry pi.  

My primary dns is on X86 docker containers and i want to replicate it on the raspberry Pi.
Pihole -> lancache-dns -> unbound -> upstream resolver.

### Output of docker run

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform(linux/arm64/v8) and no specific platform was requested.
```

**Comment by VibroAxe** [comment]
> 

For reference you didn't need to edit the tags/name it as 'my-lancache'. To build the image on arm you could have used the following:

```
git clone https://github.com/lancachenet/ubuntu.git
cd ubuntu
docker image build . --tag lancachenet/ubuntu:latest
git clone https://github.com/lancachenet/lancache-dns.git
cd lancache-dns
docker image build . --tag lancachenet/lancache-dns:latest
```

**Comment by VibroAxe** [comment]
Closing this as maintaining non architecture specific images isn't currently in the pipeline, and it is easy to self build as above
