### ISSUE TITLE
Support console caching

### ISSUE THREAD

**Issue by 0xlord** [lancachenet/lancache-dns#142]
### Describe the issue you are having
I've seen that you have/had entries for Nintendo/Sony/Microsoft (XBox). We've tested the LANcache setup within a gamesroom. PCs are working well with the caching for Steam services, but consoles aren't utilizing the cache. We've confirmed this with Nintendo and Sony consoles. But I couldn't see that MS consoles would support lancache at this point. Is there any way you would be willing to look into this issue?
I will receive a Switch to debug this to help out. Which would be our main use case. But also open to help with PS4/5 and XBox One/Series.

### How are you running the container(s)
Unraid Official Docker setup

### DNS Configuration
opnsense Router -DHCP-> lancache-dns --> lancache-monilith --> Router Unbound --> Quad 8/Quad 9

### Output of container(s)
None on this matter

**Comment by 0xlord** [comment]
As a follow up, we've  looked into the connections and Nintendo seems to use HTTPS traffic for their content delivery. With this we can go ahead and close this ticket already as I don't think that Sony and MS would do anything different. 
However, a lot of traffic was routed through lancache-monolithic as the domains used by lancache-dns are still valid :)

**Comment by VibroAxe** [comment]
@0xlord fyi, sony is cached as is some microsoft. Nintendo is out as you'd guessed!
