### ISSUE TITLE
Merge dnsmasq down to master

### ISSUE THREAD

**Issue by astrolox** [lancachenet/lancache-dns#17]
Pull request #16 gave us a version of this image which uses dnsmasq and incorporates a lot of improvements.

However there is a change of behaviour here in that the image loses the ability to do recursive lookups, instead preferring the use of an upstream DNS server.

Simply merging to master will break setups which update their docker image without knowing about this change.

So ... need a plan.

**Comment by grm** [comment]
Hello,

I just installed steamcache and my local network, and when i switch my dns to the docker image, it seems that i cannot resolve any name server anymore.
So i guess, I am facing this issue :)

How can I solve it ?
Thanks for your help.
