### ISSUE TITLE
DNS not resolving for anything

### ISSUE THREAD

**Issue by i00** [lancachenet/lancache-dns#55]
Issue Description:
I think that this issue is different than the others as the other posts seem to be related to not resolving certain domains, but mine won't resolve any to the local server - it just returns the real servers IP ... even cs.steampowered.com

My DNS settings are set (and checked) to only use 192.168.254.1 (the steamcache-dns)
I have run ipconfig /flushdns
I have tried with and without setting UPSTREAM_DNS

Any ideas? Thanks

Docker Container Output:
```
Setting up steam -> 192.168.254.2
...
10-Nov-2018 11:04:36.624 zone cs.steampowered.com/IN: loaded serial 2018111004
```

**Comment by VibroAxe** [comment]
What do you get as the output from the following in windows cmd.exe

```nslookup valve477.steamcontent.com 192.168.254.1```

**Comment by i00** [comment]
The problem is that your server list is not complete...
It doesn't list Australian servers,
If I change my servers to the UK it works...
Not good for LANs though, since people have to manually set it to use UK or US over here.

**Comment by JasonRivers** [comment]
Do you have a list of domains that are not listed for your region? If you do you can create a PR over at https://github.com/uklans/cache-domains and they will automatically get pulled by the DNS image at startup.

If we don't have a list of domains to add, we are unable to add them in.

**Comment by unspec** [comment]
Closing as inactive, plus due to new built in steam support - see https://github.com/lancachenet/monolithic/issues/85 - Steam should now redirect correctly to cache regardless of location.
