### ISSUE TITLE
can i change uklans/cache-domain to something/domain?

### ISSUE THREAD

**Issue by nyemenzo** [lancachenet/lancache-dns#68]

**Comment by VibroAxe** [comment]
Hey @nyemenzo this isn't currently supported, will see what we can do

**Comment by some-username-here1** [comment]
I think I got this down as explained and shown in PR #71, but it's still a work in progress

does that count?

**Comment by VibroAxe** [comment]
the latest version will allow you to specify `CACHE_DOMAINS_REPO="path to your git server"`

**Comment by pauls06** [comment]
I'm having issues with this. 
Downloaded cache-domains is always uklans/cache-domains
I've verified the env variable is correctly set to my repo in the lancache-dns docker instance. 
I'm not up to full speed on git, but it seems to have issues cloning in non-empty folder and cloning from within my docker instance does not support https, so i don't think overlay/hooks/entrypoint-pre.d/10_generate_config.sh will overwrite the initial git clone performed in the docker.
The initial git clone in the Dockerfile (line 12) uses https://github.com/uklans/cache-domains/ 
Should this be $CACHE_DOMAINS_REPO ?
