### ISSUE TITLE
Steam cache fails on multi-download

### ISSUE THREAD

**Issue by NoSnow3** [lancachenet/lancache-dns#74]
Issue Description:
Steamcache-dns appears to fail to redirect download sources, (Steam reports no download source available)

After having a fresh cache, Downloading one other game and then downloading frostpunk to prime the system, deleting frost punk and then re-downloading it, all appears normal, after re-downloading from the cache for a second time the steam client stalls and claims no download source available.

Docker Run Command:
```
sudo docker run --name steamcache-dns --restart=always -d -p 192.168.0.10:53:53/udp -e STEAMCACHE_IP="192.168.0.10 192.168.0.11 192.168.0.12 192.168.0.13 192.168.0.14 192.168.0.15 192.168.0.16 192.168.0.17 192.168.0.18 192.168.0.19" steamcache/steamcache-dns:latest

sudo docker run --name steamcache --restart=always -d -v /srv/steamcache/data:/data/cache -p 80:80 steamcache/monolithic:latest

```

Logs:
Steamcache-dns: https://pastebin.com/XwC8WZD9
Monolithic Log: https://pastebin.com/nbq4qygE
Steam Client content Log: https://pastebin.com/5pTqNrNC

**Comment by VibroAxe** [comment]
looks like you are missing sniproxy?

**Comment by NoSnow3** [comment]
It was running I thought, anyway. The problem ended up being memory errors
