### ISSUE TITLE
CONSTANT restarting

### ISSUE THREAD

**Issue by Kore-Development** [lancachenet/lancache-dns#83]
Issue Description:
Constantly restarts the container
![](https://i.imgur.com/HFFutaD.png)

Docker Run Command:
```
export LANCACHE_IP=`hostname -I | cut -d' ' -f1`
docker run --restart unless-stopped --name lancache -v /cache/data:/data/cache -v /cache/logs:/data/logs -p 80:80 lancachenet/monolithic:latest
docker run --restart unless-stopped --name lancache-dns -p 53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=$LANCACHE_IP lancachenet/lancache-dns:latest
docker run --restart unless-stopped --name lancache-sniproxy -p 443:443 lancachenet/sniproxy:latest
echo Please configure your dhcp server to serve dns as $HOST_IP
```

Docker Container Output:

```
No errors
```

I have never used Docker.

**Comment by Kore-Development** [comment]
and going to http://54.39.252.122/ comes up with HTTP error 508

**Comment by VibroAxe** [comment]
What's the output of `docker logs lancache-dns`

**Comment by Kore-Development** [comment]
@VibroAxe 
```
     _                                      _                       _   
    | |                                    | |                     | |  
 ___| |_ ___  __ _ _ __ ___   ___ __ _  ___| |__   ___   _ __   ___| |_ 
/ __| __/ _ \/ _` | '_ ` _ \ / __/ _` |/ __| '_ \ / _ \ | '_ \ / _ \ __|
\__ \ ||  __/ (_| | | | | | | (_| (_| | (__| | | |  __/_| | | |  __/ |_ 
|___/\__\___|\__,_|_| |_| |_|\___\__,_|\___|_| |_|\___(_)_| |_|\___|\__|



If you are using USE_GENERIC_CACHE then you must set LANCACHE_IP
```
Repeated

**Comment by VibroAxe** [comment]
You cache container didn't manage to find the ip of your cache.

What's the output of `hostname -I | cut -d' ' -f1` and `hostname -I`

**Comment by Kore-Development** [comment]
![image](https://user-images.githubusercontent.com/29719362/59151269-bc42d480-89f5-11e9-9447-623b3affe6eb.png)

**Comment by Kore-Development** [comment]
@VibroAxe ![image](https://user-images.githubusercontent.com/29719362/59151269-bc42d480-89f5-11e9-9447-623b3affe6eb.png)

**Comment by VibroAxe** [comment]
Do all the machines on your network have a public IP?
Is this machine inside your network, you can't have a cache box external to the network

Assuming this is an internal cache however:

For some reason LANCACHE_IP wasn't set when you ran the commands. My guess is you forgot the export line

```docker stop lancache-dns
docker rm lancache-dns

docker run --restart unless-stopped --name lancache-dns -p 53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=54.39.252.122 lancachenet/lancache-dns:latest```
Should get you up and running

**Comment by hAxx** [comment]
> Do all the machines on your network have a public IP?
> Is this machine inside your network, you can't have a cache box external to the network
> 
> Assuming this is an internal cache however:
> 
> For some reason LANCACHE_IP wasn't set when you ran the commands. My guess is you forgot the export line
> 
> ```
> docker stop lancache-dns
> docker rm lancache-dns
> 
> docker run --restart unless-stopped --name lancache-dns -p 53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=54.39.252.122 lancachenet/lancache-dns:latest
> ```
> 
> Should get you up and running

this helped me. Thanks

**Comment by HerrSammyDE** [comment]
I had the same problem.

The log then said that 53:53/udp is already in use. This is also correct, from the Debian server itself.

How can I change this? It is an external server and has no internal network to the other server

**Comment by astrolox** [comment]
@HerrSammyDE  I think the solution to your problem is to stop the dns server which Debian is running for you. Logically you only need one dns server, it's either this one or that one.

Also just because the symptom is the same (constant restarting) doesn't mean the cause is the same. Locking thread.
