### ISSUE TITLE
[Feature Request] Support Multiple Upstream DNS

### ISSUE THREAD

**Issue by msmollin** [lancachenet/lancache-dns#84]
First, great project. I use the full stack with monolithic and it makes our internet connection usable during our LAN parties.

That said, it'd be stellar if I could have multiple upstream DNS IPs support. I tried doing it like the STEAMCACHE_DNS space separated list for multiple IPs but got the following error:
```/etc/bind/named.conf.options:12: missing ';' before '8.8.4.4'```

Is it as simple as putting a semicolon in between the IPs? I'm familiar with BIND's configuration in a caching / forwarding setup, but am unsure how the docker commands are injected into the config? If it's as simple as adding a `;`, then I'll just put in a PR on the README to document it (when I ultimately forget how it all works). 

Thanks much!

**Comment by VibroAxe** [comment]
We'll have to add this as new functionality to split the UPSTREAM_DNS

Technically for the moment the following should work as a short term fix
`UPSTREAM_DNS="8.8.8.8; nameserver 8.8.4.4;"`

**Comment by Deanosim** [comment]
Okay after much trial and error I worked out that the correct syntax is 
`UPSTREAM_DNS=8.8.8.8; 8.8.4.4`
And if you want to use a custom port like me for cloudflared it is 
`UPSTREAM_DNS=192.168.1.202 port 5054; 1.1.1.1`
The last entry in the line doesn't need a ; as that's already defined in the config.

**Comment by Deanosim** [comment]
Didn't realize till now, but the port number doesn't work, not sure if I should open another issue about this, but from what I can tell the lancache-dns docker doesn't allow custom ports on the Upstream DNS servers.

**Comment by GotenXiao** [comment]
@VibroAxe Was this fixed by #101?

**Comment by VibroAxe** [comment]
Yeah, don't know why it didn't close the issue
