### ISSUE TITLE
 Error response from daemon: failed to create endpoint 

### ISSUE THREAD

**Issue by hades200082** [lancachenet/lancache-dns#89]
**Issue Description:**
The container is created but fails to bind port 53. 

The dockerd service has port 53 bound which correlates with https://docs.docker.com/v17.09/engine/userguide/networking/configure-dns/

How can we resolve this and allow the lancache-dns container to work as intended on a Windows container with LCOW?

**Docker Run Command:**

```
docker run --platform linux --restart unless-stopped --name lancache-dns --detach -p 192.168.1.200:53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=192.168.1.200 lancachenet/lancache-dns:latest
```

**Docker Container Output:**

```
C:\Program Files\Docker\docker.exe: Error response from daemon: failed to create endpoint lancache-dns on network nat: Windows does not support host IP addresses in NAT settings.
```

**Comment by dark-swordsman** [comment]
I was/am having a similar issue over here: https://github.com/lancachenet/lancache-dns/issues/81

It looks like, for some reason, even after disabling the dns-server-thing in Linux that was binding port 53, the port isn't being remapped to the docker container.

I haven't touched our test VM in a while, but I'm having a meeting later today to decide what to do going forward and look into options. I'll update on my issue and respond to Vibro's question.

**Comment by hades200082** [comment]
This is specifically a problem in Windows when using Docker Windows containers + LCOW

In a Linux host you can specify the IP to which port 53 should bind and all is well. This doesn't work for a Windows host as the dockerd service its self has bound all IPs to port 53 its self.

**Comment by astrolox** [comment]
We had intended lancache to be run on Linux. You're welcome to run it on Windows, but it's not something we've ever tried to do.

This will need research. 
It sounds to me like you're saying that it isn't possible to run a DNS server in docker on windows. I don't know if that's true or not - but if it is you'll need an alternative to lancache-dns that does the same /similar job. Any windows based DNS server can do this job - however you will need to find a way to configure it.
