### ISSUE TITLE
[Feature Request] Add DNS over HTTPS support

### ISSUE THREAD

**Issue by tuzzmaniandevil** [lancachenet/lancache-dns#90]
I found a very handy guide to configure dnsmasq to use DNS over HTTPS.

https://bendews.com/posts/implement-dns-over-https/

It would be great if this could somehow be integrated into the project :-)

**Comment by astrolox** [comment]
Is this needed?
What are the benefits? 
What problems would be solved?

**Comment by tuzzmaniandevil** [comment]
It adds a privacy layer. Normally I would set up DNS over HTTPS on the router so all devices on the LAN side use it by default. But because the router now points to the lancache server and that makes the external DNS requests, that privacy layer disappears.

**Comment by astrolox** [comment]
Personally I would advise the following;
- Have your router doing your preferred way of performing DNS
- Use the upstream `UPSTREAM_DNS` feature of lancache-dns to specify that lancache should use your router as it's upstream DNS server
- Use DHCP to tell your the devices on your LAN to use lancache as their DNS server

This way you can control how you want DNS lookups outside your network to be performed.

**Comment by astrolox** [comment]
Ok, you got me curious so I did a little more research. 
DNS over HTTPS is indeed interesting, although not perfect.

In relation to the solution you linked to and other solutions I found, an additional daemon needs to be run to act as a DNS over HTTPS proxy. Usually, but not always, the cloudflared is used.

I think it would be inappropriate to include this additional software in the lancache-dns image. On the basis that each docker image should have a [single responsibility](https://en.wikipedia.org/wiki/Single_responsibility_principle), in an ideal world. We aren't trying to make the world's best DNS server image, we're just trying to provide an easy way to MITM DNS for the purposes of redirecting traffic to the cache. 

_Honestly it were possible to provide caching without this I would prefer that solution (yes, that is something we've been looking in to and have been experimenting with)._

So such I'm going to close this feature request. However I want to thank you for your contribution - please continue to be a part of the community.

For anyone who wishes to incorporate DNS over HTTPs in to their lancache setup please note that the advice I gave above in relation to the `UPSTREAM_DNS` feature we have included in this image. Additionally please note that you can run a separate container with the DNS proxy in it, as use that as your upstream (think microservices!).
