### ISSUE TITLE
Windows Update / Microsoft Store denying Updates, Affecting some Windows Store Games aswell

### ISSUE THREAD

**Issue by wofnull** [lancachenet/lancache-dns#98]
Issue Description:
Problem faced up around 1 or 2 months ago and started with problems getting Windows Updates to work on fresh installed computers aswell as on already existing ones. Affected was everytime Windows 10 Update Service aswell as Windows Store Updates.

At a later time, Forza Horizon 4 ( uses Windows Store to update) gave Error Messages ingame that Updates cannot be  pulled and denied Online Play mode, after switching DNS Off and a quick Windows Update / Windows Store Update the Game was able to start and Windows Update / Windows Store / Game was able to start even with DNS Redirect on again.

Logs at Steamcache from a client without DNS off trick trying to pull windows  Updates:

`[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:31:15 +0200] "GET /msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab?9e538df4c5a38d4c HTTP/1.1" 304 0 "-" "Microsoft-CryptoAPI/10.0" "HIT" "ctldl.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:31:51 +0200] "GET /msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab?01ef244044f118f7 HTTP/1.1" 304 0 "-" "Microsoft-CryptoAPI/10.0" "HIT" "ctldl.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:32:55 +0200] "GET /msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab?4780b5a5518c70b7 HTTP/1.1" 304 0 "-" "Microsoft-CryptoAPI/10.0" "HIT" "ctldl.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:33:05 +0200] "GET /msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab?a3e27f82e85335a6 HTTP/1.1" 200 6529 "-" "Microsoft-CryptoAPI/10.0" "HIT" "ctldl.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:33:08 +0200] "GET /msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab?cebda6c122fd796d HTTP/1.1" 304 0 "-" "Microsoft-CryptoAPI/10.0" "HIT" "ctldl.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:33:12 +0200] "GET /msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab?2b4bcaffe317f920 HTTP/1.1" 200 6529 "-" "Microsoft-CryptoAPI/10.0" "HIT" "ctldl.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:33:21 +0200] "GET /msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab?1e3048541614f5b6 HTTP/1.1" 304 0 "-" "Microsoft-CryptoAPI/10.0" "HIT" "ctldl.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:33:25 +0200] "GET /msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab?3d5b66c226c48185 HTTP/1.1" 304 0 "-" "Microsoft-CryptoAPI/10.0" "HIT" "ctldl.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:33:36 +0200] "GET /msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab?e4a3d104c5f0b95a HTTP/1.1" 304 0 "-" "Microsoft-CryptoAPI/10.0" "HIT" "ctldl.windowsupdate.com" "-"
[wsus] 192.168.178.120 / - - - [21/Oct/2019:19:33:47 +0200] "GET /msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab?177b76fdf9098cc7 HTTP/1.1" 304 0 "-" "Microsoft-CryptoAPI/10.0" "HIT" "ctldl.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:33:51 +0200] "GET /msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab?36c48652b85ba2ef HTTP/1.1" 304 0 "-" "Microsoft-CryptoAPI/10.0" "HIT" "ctldl.windowsupdate.com" "-"
[wsus] 192.168.178.120 / - - - [21/Oct/2019:19:37:46 +0200] "GET /msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab?4930893428fe216c HTTP/1.1" 200 6529 "-" "Microsoft-CryptoAPI/10.0" "HIT" "ctldl.windowsupdate.com" "-"
`

Example from a client after the DNS Off and on again after "Auth" way:

`[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:25 +0200] "GET /c/msdownload/update/others/2019/10/30117433_54f3d3d243d715b1bad5fce8a8634f395419fe9e.cab HTTP/1.1" 200 7173 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:25 +0200] "GET /c/msdownload/update/others/2019/10/30117432_208508059bd711141fbd80cc91863155879f505d.cab HTTP/1.1" 200 7163 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:25 +0200] "GET /c/msdownload/update/others/2019/10/30116983_851b8d3ca745794251346b9f0392af17d157cfbc.cab HTTP/1.1" 200 7177 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:25 +0200] "GET /c/msdownload/update/others/2019/10/30116982_34daf15b2976defdabb958ad1df60a80f536c183.cab HTTP/1.1" 200 7169 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:25 +0200] "GET /d/msdownload/update/others/2019/10/30119502_24c5cd5ef28173640e481e8474fa0177547cd0cb.cab HTTP/1.1" 200 10419 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:25 +0200] "GET /d/msdownload/update/others/2019/10/30119055_1ebc38f3ad28c3ce5cd6d2ff518cd90ec67fd0e9.cab HTTP/1.1" 200 10429 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:25 +0200] "GET /c/msdownload/update/others/2019/10/30118494_09c7fe324efb18c1df06e27370ce7e84c6348567.cab HTTP/1.1" 200 10565 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:25 +0200] "GET /d/msdownload/update/others/2019/10/30118004_898ed5df25d3b798e9e95a84aa034ea3ed2bafd7.cab HTTP/1.1" 200 10545 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:25 +0200] "GET /c/msdownload/update/others/2019/10/30117549_11cbdef1538f7fef24a69a1d5eb7411e04bee7af.cab HTTP/1.1" 200 10565 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:25 +0200] "GET /c/msdownload/update/others/2019/10/30117099_4a023ec3d356f392cbcfbf4a1b83b43e6d4af51a.cab HTTP/1.1" 200 10563 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:26 +0200] "GET /c/msdownload/update/others/2019/10/30118378_201b6789b7a1048581d0da71c877c72ccd9fe527.cab HTTP/1.1" 200 7171 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:26 +0200] "GET /c/msdownload/update/others/2019/10/30118377_c038f5c713171b0ae0ebb79f6c513237056b1308.cab HTTP/1.1" 200 7165 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:26 +0200] "GET /d/msdownload/update/others/2019/10/30117888_8972d42da177ae3170aa3b6d7cafd658ccacbdaf.cab HTTP/1.1" 200 7171 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:26 +0200] "GET /d/msdownload/update/others/2019/10/30117887_943b2c6e22e8face71bc9507b13bc62d185032a2.cab HTTP/1.1" 200 7167 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:27 +0200] "GET /d/msdownload/update/others/2019/10/30119391_8aeebca4aa05259f6823331851e52973fb1c00a2.cab HTTP/1.1" 200 7173 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:27 +0200] "GET /d/msdownload/update/others/2019/10/30119390_67a93900a1bfbfa6abe411caedb98e6e6e33c52e.cab HTTP/1.1" 200 7171 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:27 +0200] "GET /d/msdownload/update/others/2019/10/30118944_5bf2301aa5b45990642cffe4b338bf7a10ec6d6b.cab HTTP/1.1" 200 7169 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:27 +0200] "GET /d/msdownload/update/others/2019/10/30118943_1d4149adb847035c66175cbe5eb7572758ebfa51.cab HTTP/1.1" 200 7171 "-" "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.0" "MISS" "download.windowsupdate.com" "-"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:31 +0200] "GET /c/msdownload/update/software/defu/2019/10/am_delta_b4fc585a4a40ca9e4b08dc62e033fd66aca1162b.exe HTTP/1.1" 206 2 "-" "Microsoft-Delivery-Optimization/10.0" "MISS" "au.download.windowsupdate.com" "bytes=0-1"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:31 +0200] "GET /c/msdownload/update/software/defu/2019/10/am_delta_b4fc585a4a40ca9e4b08dc62e033fd66aca1162b.exe HTTP/1.1" 206 1048576 "-" "Microsoft-Delivery-Optimization/10.0" "HIT" "au.download.windowsupdate.com" "bytes=0-1048575"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:31 +0200] "GET /c/msdownload/update/software/defu/2019/10/am_delta_b4fc585a4a40ca9e4b08dc62e033fd66aca1162b.exe HTTP/1.1" 206 1048576 "-" "Microsoft-Delivery-Optimization/10.0" "MISS" "au.download.windowsupdate.com" "bytes=5242880-6291455"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:31 +0200] "GET /c/msdownload/update/software/defu/2019/10/am_delta_b4fc585a4a40ca9e4b08dc62e033fd66aca1162b.exe HTTP/1.1" 206 1048576 "-" "Microsoft-Delivery-Optimization/10.0" "MISS" "au.download.windowsupdate.com" "bytes=1048576-2097151"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:31 +0200] "GET /c/msdownload/update/software/defu/2019/10/am_delta_b4fc585a4a40ca9e4b08dc62e033fd66aca1162b.exe HTTP/1.1" 206 1048576 "-" "Microsoft-Delivery-Optimization/10.0" "MISS" "au.download.windowsupdate.com" "bytes=4194304-5242879"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:31 +0200] "GET /c/msdownload/update/software/defu/2019/10/am_delta_b4fc585a4a40ca9e4b08dc62e033fd66aca1162b.exe HTTP/1.1" 206 1048576 "-" "Microsoft-Delivery-Optimization/10.0" "MISS" "au.download.windowsupdate.com" "bytes=3145728-4194303"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:31 +0200] "GET /c/msdownload/update/software/defu/2019/10/am_delta_b4fc585a4a40ca9e4b08dc62e033fd66aca1162b.exe HTTP/1.1" 206 393928 "-" "Microsoft-Delivery-Optimization/10.0" "MISS" "au.download.windowsupdate.com" "bytes=6291456-6685383"
[wsus] 192.168.178.30 / - - - [21/Oct/2019:19:48:31 +0200] "GET /c/msdownload/update/software/defu/2019/10/am_delta_b4fc585a4a40ca9e4b08dc62e033fd66aca1162b.exe HTTP/1.1" 206 1048576 "-" "Microsoft-Delivery-Optimization/10.0" "MISS" "au.download.windowsupdate.com" "bytes=2097152-3145727"
`

Looks like somehow Windows Update / Storefront trys to pull a certificate which is declined if the request runs through the lancache-dns / lancache/monolithic container.

**Comment by mmischitelli** [comment]
same happening on my configuration
